package com.atmostadam.cats.drools

import com.atmostadam.cats.api.model.in.CatRequest;
import com.atmostadam.cats.api.model.out.CatResponse;
import com.atmostadam.cats.api.model.Microchip;

dialect "java"

rule "Create Test Cat Request"
agenda-group "cat-request-rules"
no-loop
    when
    	$request : CatRequest()
    	$microchip : Microchip(microchipNumber == null)
    then
        $microchip.setMicrochipNumber($request.getCats().get(0).getMicrochip().getMicrochipNumber());
		update($microchip);
end


rule "Create Test Cat Response"
agenda-group "cat-response-rules"
no-loop
    when
    	$response : CatResponse()
    then
        $response.setMessage("200");
		update($response);
end
